import Head from 'next/head'
import BasicTable from '../src/EnhancedTable'
import { useState ,useEffect} from 'react'
import { DataStore } from '@aws-amplify/datastore'
import {Event} from './../models'

function Home({data}) {
  const [events, setEvents] = useState([]);
  useEffect(() => {
    fetchEvents()   
    async function fetchEvents (){
      const evensData = await DataStore.query(Event);
     setEvents(evensData)
    }
  }, [])



  return (
    <div>
      <Head>
        <title>Bessppl - High Performance Software Engineering Training and Super Efficient Team Building </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
        High Performance Software Engineering Training and Super Efficient Team Building 
        </h1>
        <BasicTable data={events} />
      </main>
    </div>
  )
}

// Home.getInitialProps = async (ctx) => {
//   const res = await fetch('https://app.bessppl.com/events')
//   const data = await res.json()
//   return { data }
// }

export default Home;
