import Head from 'next/head'
//import Image from 'next/image'
//import BasicTable from '../src/EnhancedTable'

// const url = 'http://us-api.bessppl.com/events'

// export async function getServerSideProps() {
//   const res = await fetch(url)
//   const data = await res.json()
//   return {
//     props: { data }
//   }
// }

export default function Home({data}) {
  return (
    <div>
      <Head>
        <title>Bessppl - High Performance Software Engineering Training and Super Efficient Team Building </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
        High Performance Software Engineering Training and Super Efficient Team Building 
        </h1>
        {/* <BasicTable data={data} /> */}
      </main>
    </div>
  )
}
