import Head from 'next/head'
import BasicTable from '../src/EnhancedTable'

function Home({data}) {
  return (
    <div>
      <Head>
        <title>Bessppl - High Performance Software Engineering Training and Super Efficient Team Building </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
        High Performance Software Engineering Training and Super Efficient Team Building 
        </h1>
      </main>
    </div>
  )
}

export default Home;
